[package]
name = "kestara-webrtc-native"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
description = "Native WebRTC runtime for Kestara WebRTC"
license = "MIT OR Apache-2.0"
repository = "https://github.com/enderdash-com/kestara-webrtc"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.89"
bytes = "1.12.0"
crossbeam-channel = "0.5.15"
jni = "0.22.4"
rcgen = "0.14.9"
rtc = { git = "https://github.com/enderdash-com/rtc.git", rev = "81a8ba796d058daa07771eb9160ad411724c3cbe", features = ["pem"] }
ice = { package = "rtc-ice", git = "https://github.com/enderdash-com/rtc.git", rev = "81a8ba796d058daa07771eb9160ad411724c3cbe" }
tokio = { version = "1.52.0", features = ["rt-multi-thread", "time"] }
webrtc = { git = "https://github.com/enderdash-com/webrtc.git", rev = "18bf3d45cb284d1b18971de757874da51e075096" }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "deny"
pedantic = "deny"
